# Generated by Django 3.2.7 on 2021-09-19 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('phone', models.CharField(max_length=16)),
                ('addtime', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'myapp_users',
            },
        ),
    ]
