# Generated by Django 3.2.7 on 2021-09-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Users1',
        ),
        migrations.AlterModelTable(
            name='users1',
            table='myapp_users_test',
        ),
    ]
