# Generated by Django 3.2.7 on 2021-09-19 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210919_1238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users1',
            new_name='Users',
        ),
    ]
